spring:
  application:
    name: eureka-register-center-8003
  security:
    basic:  # 开启基于HTTP basic认证
      enabled: true
    user:
      name: root          # 用户名
      password: 123456    # 密码


server:
  port: 8003
eureka:
  instance:
    hostname: enodethree.com # eureka的服务端实例名称
    preferIpAddress: true #
  client:
    registerWithEureka: false # 是否将自己注册到eureka中
    fetchRegistry: false # 不需要进行检索【发现】服务
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
# 设置Eureka Server交互地址 查询服务注册中心 单机版本
      defaultZone: http://enodetwo.com:8002/eureka/, http://enodeone.com:8001/eureka/ # 集群版本
#      defaultZone: http://e8001/eureka/, http://e8002/eureka/ # 集群docker版本
    healthcheck:
      enabled: true
    eurekaServiceUrlPollIntervalSeconds: 60

